# Generated by Django 5.0 on 2024-01-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restoapp', '0003_cart_order_product_delete_resto_order_pid_cart_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'VEG'), (2, 'NON-VEG'), (3, 'SWEET')], verbose_name='Category'),
        ),
    ]
